"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";

/**
 * Client-side search across all indexed filings.
 *
 * Static-export-compatible: fetches the prebuilt /api/filings.json index
 * (generated by scripts/generate-api-json.ts at build time), then filters
 * in-memory on every keystroke. URL-shareable via ?q= param so search
 * results are bookmarkable + linkable from external sites + LLM citations.
 *
 * Match strategy: case-insensitive substring across cleaned filer name,
 * ticker, form type, accession number, CIK. No external search service =
 * no per-query API cost = no cold-start latency.
 *
 * Archetype: core_loop_improvement (Retention Oracle ×+0.060) — the
 * primary "thing users come back for" on a database-surface site.
 */

interface ApiFiling {
  accession_number: string;
  cik: string;
  filer_name: string;
  form_type: string;
  filed_at: string;
  url: string;
}

interface ApiFilingsIndex {
  count: number;
  filings: ApiFiling[];
}

// Stripe " (TICKER) (CIK 0000000000)" suffix for cleaner display.
function cleanFilerName(raw: string): string {
  return raw
    .replace(/\s*\(CIK\s+\d+\)\s*$/i, "")
    .replace(/\s*\([A-Z][A-Z0-9.\-]{0,8}(?:,\s*[A-Z][A-Z0-9.\-]{0,8})*\)\s*/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function extractTicker(raw: string): string | null {
  const m = raw.match(/\(([A-Z][A-Z0-9.\-]{0,8})(?:,\s*[A-Z][A-Z0-9.\-]{0,8})*\)/);
  return m ? m[1] : null;
}

function formatDateShort(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export function SearchClient() {
  const searchParams = useSearchParams();
  const initialQuery = searchParams.get("q") ?? "";

  const [query, setQuery] = useState(initialQuery);
  const [filings, setFilings] = useState<ApiFiling[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement | null>(null);

  // Fetch index once on mount.
  useEffect(() => {
    let alive = true;
    fetch("/api/filings.json")
      .then((r) => {
        if (!r.ok) throw new Error(`status ${r.status}`);
        return r.json() as Promise<ApiFilingsIndex>;
      })
      .then((data) => {
        if (alive) setFilings(data.filings);
      })
      .catch((e: unknown) => {
        if (alive) setError(e instanceof Error ? e.message : String(e));
      });
    return () => {
      alive = false;
    };
  }, []);

  // Auto-focus on mount (consistent with what users expect on /search/).
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  // Sync query → URL (?q=...). Replace state to avoid history-spam on every keystroke.
  useEffect(() => {
    const trimmed = query.trim();
    const url = trimmed ? `/search/?q=${encodeURIComponent(trimmed)}` : "/search/";
    // Only update if it actually changed (initial-render parity).
    if (typeof window !== "undefined") {
      const current = window.location.pathname + window.location.search;
      if (current !== url) {
        // Native history, not router.replace: the router fetches /search/index.txt?_rsc, which
        // prune-out.mjs deletes, and the 404 forced a full reload on each keystroke (2026-09-24:
        // typing "SYY" reloaded twice and the page kept "SY").
        window.history.replaceState(null, "", url);
      }
    }
  }, [query]);

  // Microsoft Clarity custom event — fire `search` once per stable query (≥3 chars,
  // settled for 800ms). Heuristic for "the user actually intended to search" rather
  // than every keystroke. Skipped if Clarity not loaded (consent-gated).
  useEffect(() => {
    const q = query.trim();
    if (q.length < 3) return;
    const t = setTimeout(() => {
      if (typeof window !== "undefined" && typeof window.clarity === "function") {
        window.clarity("event", "search");
      }
    }, 800);
    return () => clearTimeout(t);
  }, [query]);

  const matches = useMemo(() => {
    if (!filings) return [];
    const q = query.trim().toLowerCase();
    if (!q) return filings.slice(0, 20);

    const tokens = q.split(/\s+/).filter(Boolean);

    return filings.filter((f) => {
      const haystack = [
        f.accession_number,
        f.cik,
        f.form_type,
        f.filer_name,
      ]
        .join(" ")
        .toLowerCase();
      return tokens.every((t) => haystack.includes(t));
    });
  }, [filings, query]);

  const totalCount = filings?.length ?? 0;
  const matchCount = matches.length;
  const showingCap = !query.trim() && filings && matchCount < totalCount;

  return (
    <div className="space-y-6">
      {/* Search input — full width, large tap target on mobile */}
      <div className="relative">
        <input
          ref={inputRef}
          type="search"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search by filer, ticker, accession, CIK, or form type…"
          aria-label="Search filings"
          spellCheck={false}
          autoComplete="off"
          autoCorrect="off"
          className="w-full min-h-[52px] px-5 py-3.5 rounded-card-lg border border-border bg-panel/40 text-text text-body-lg placeholder:text-dim focus:outline-none focus:border-brand focus:ring-2 focus:ring-brand/30 transition-colors"
        />
      </div>

      {/* Status row */}
      <p className="text-body-sm text-muted tabular">
        {!filings && !error && "Loading filings…"}
        {error && (
          <span className="text-signal-amend">
            Couldn&apos;t load filings index ({error}). Refresh or try again.
          </span>
        )}
        {filings && !query.trim() && (
          <>
            <span className="text-text font-medium">{totalCount}</span>{" "}
            filings indexed{showingCap ? `. Showing the most recent ${matchCount}.` : "."}
          </>
        )}
        {filings && query.trim() && matchCount > 0 && (
          <>
            <span className="text-text font-medium">{matchCount}</span>{" "}
            {matchCount === 1 ? "match" : "matches"} for{" "}
            <span className="font-mono text-text">&ldquo;{query.trim()}&rdquo;</span>
          </>
        )}
        {filings && query.trim() && matchCount === 0 && (
          <>
            No matches for{" "}
            <span className="font-mono text-text">&ldquo;{query.trim()}&rdquo;</span>.
            Try filer name, ticker, accession number, CIK, or form type.
          </>
        )}
      </p>

      {/* Results */}
      {filings && matches.length > 0 && (
        <div className="rounded-card-lg border border-border bg-panel/40 overflow-hidden">
          <ul className="divide-y divide-border">
            {matches.map((f) => {
              const filer = cleanFilerName(f.filer_name);
              const ticker = extractTicker(f.filer_name);
              return (
                <li key={f.accession_number}>
                  <Link
                    href={`/filing/${f.accession_number}/`}
                    className="flex flex-col sm:flex-row sm:items-baseline gap-1 sm:gap-4 px-5 py-4 min-h-[60px] hover:bg-surface-hover transition-colors"
                  >
                    <time
                      dateTime={f.filed_at}
                      className="font-mono text-data-cell text-dim sm:w-28 shrink-0 tabular"
                    >
                      {formatDateShort(f.filed_at)}
                    </time>
                    <span className="font-mono text-data-cell text-brand sm:w-24 shrink-0">
                      {f.form_type}
                    </span>
                    <span className="text-text flex-1 break-words">
                      {filer}
                      {ticker && (
                        <span className="ml-2 font-mono text-data-cell text-muted">
                          {ticker}
                        </span>
                      )}
                    </span>
                    <span className="hidden sm:inline font-mono text-caption text-dim shrink-0">
                      {f.accession_number}
                    </span>
                  </Link>
                </li>
              );
            })}
          </ul>
        </div>
      )}
    </div>
  );
}
